version: '3.8'

services:
  # 🐰 Message Queue
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rentacar-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - rentacar-network

  # 🚪 API Gateway
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: rentacar-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"  # Main entry point
    environment:
      PORT: 3000
      AUTH_SERVICE_URL: http://rentacar-auth-service:5001
      CAR_SERVICE_URL: http://rentacar-car-service:5002 # Yeni eklenen servis
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:3001}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      - auth-service
      - car-service # Gateway'in başlamadan önce car-service'i beklemesini sağlar
    networks:
      - rentacar-network

  auth-service:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
    container_name: rentacar-auth-service
    restart: unless-stopped
    expose:
      - "5001"
    environment:
      MONGODB_URI: ${MONGODB_URI_AUTH} # <-- Değişiklik burada
      PORT: 5001
      # ... diğer environment değişkenleri
    depends_on:
      - rabbitmq
    networks:
      - rentacar-network

  # 🚗 Car Service
  car-service:
    build:
      context: .
      dockerfile: ./services/car-service/Dockerfile
    container_name: rentacar-car-service
    restart: unless-stopped
    expose:
      - "5002"
    environment:
      MONGODB_URI: ${MONGODB_URI_CAR} # <-- Değişiklik burada
      PORT: 5002
      RABBITMQ_URI: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - rentacar-network

networks:
  rentacar-network:
    driver: bridge