version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rentacar-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - rentacar-network

  auth-service:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
    container_name: rentacar-auth-service
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PORT: 5001
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: ${JWT_EXPIRE}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      RABBITMQ_URI: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - rentacar-network
    volumes:
      # Development için sadece kaynak kodu mount et
      - ./services/auth-service/controllers:/app/controllers
      - ./services/auth-service/models:/app/models
      - ./services/auth-service/routes:/app/routes
      - ./services/auth-service/server.js:/app/server.js
      - ./shared-utils:/app/shared-utils
      # node_modules'ı korumak için
      - /app/node_modules

networks:
  rentacar-network:
    driver: bridge